id: I92CBA920
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:38:23+00:00'
last_modified: '2022-06-09T07:42:51.066155+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29246
  title: བདེ་ཆེན་འབར་བའི་རྡོ་རྗེའི་སྐུ་ཕྲེང་གཉིས་པ་ཀརྨ་བདེ་ཆེན་དགའ་བའི་ཡེ་ཤེས་ཕྲིན་ལས་ཀུན་ཁྱབ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ཉུང་ཙམ་བརྗོད་པ་སྐྱ་རིང་འཆར་ཀ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    22F4:
      image_group_id: I1KG1589
      title: Volume 1 of bde chen 'bar ba'i rdo rje'i sku phreng gnyis pa ka.rma bde
        chen dga' ba'i ye shes phrin las kun khyab dpal bzang po'i rnam par thar pa
        nyung tsam brjod pa skya ring 'char ka
      total_pages: 116
      order: 1
      base_file: 22F4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
