id: I92CBA920
legacy_id: P007935
ocr_import_info:
  bdrc_scan_id: W29246
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T19:37:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T10:19:12.840750+00:00'
last_modified: 2022-09-02 18:19:24.228885
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29246
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29246
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བདེ་ཆེན་འབར་བའི་རྡོ་རྗེའི་སྐུ་ཕྲེང་གཉིས་པ་ཀརྨ་བདེ་ཆེན་དགའ་བའི་ཡེ་ཤེས་ཕྲིན་ལས་ཀུན་ཁྱབ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ཉུང་ཙམ་བརྗོད་པ་སྐྱ་རིང་འཆར་ཀ
  author: ཀརྨ་ཐུབ་བསྟན།
statistics:
  ocr_word_mean_confidence_index: 0.9261841539153086
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG1589:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1589
      total_pages: 116
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1589.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9261841539153086
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
