id: opecha:P007935
initial_creation_type: ocr
source_metadata:
  id: bdr:W29246
  title: བདེ་ཆེན་འབར་བའི་རྡོ་རྗེའི་སྐུ་ཕྲེང་གཉིས་པ་ཀརྨ་བདེ་ཆེན་དགའ་བའི་ཡེ་ཤེས་ཕྲིན་ལས་ཀུན་ཁྱབ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ཉུང་ཙམ་བརྗོད་པ་སྐྱ་རིང་འཆར་ཀ
  volume: ''
  author: ''
