id: P007935
initial_creation_type: ocr
source_metadata:
  id: bdr:W29246
  title: བདེ་ཆེན་འབར་བའི་རྡོ་རྗེའི་སྐུ་ཕྲེང་གཉིས་པ་ཀརྨ་བདེ་ཆེན་དགའ་བའི་ཡེ་ཤེས་ཕྲིན་ལས་ཀུན་ཁྱབ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ཉུང་ཙམ་བརྗོད་པ་སྐྱ་རིང་འཆར་ཀ
  author: ''
  volumes:
    65576b02387d411bad985990d5b23e36:
      image_group_id: I1KG1589
      title: ''
      volume_number: 1
      total_pages: 116
ebook_metadata:
  title: བདེ་ཆེན་འབར་བའི་རྡོ་རྗེའི་སྐུ་ཕྲེང་གཉིས་པ་ཀརྨ་བདེ་ཆེན་དགའ་བའི་ཡེ་ཤེས་ཕྲིན་ལས་ཀུན་ཁྱབ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ཉུང་ཙམ་བརྗོད་པ་སྐྱ་རིང་འཆར་ཀ
  author: ''
  sku: P007935
  cover: cover.jpg
  layers:
  - pagination
