id: P007935
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W29246
  title: བདེ་ཆེན་འབར་བའི་རྡོ་རྗེའི་སྐུ་ཕྲེང་གཉིས་པ་ཀརྨ་བདེ་ཆེན་དགའ་བའི་ཡེ་ཤེས་ཕྲིན་ལས་ཀུན་ཁྱབ་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ཉུང་ཙམ་བརྗོད་པ་སྐྱ་རིང་འཆར་ཀ
  author: ''
  volumes:
    93eb6df62c034c4aa961a12e558e97f8:
      image_group_id: I1KG1589
      title: Volume 1 of bde chen 'bar ba'i rdo rje'i sku phreng gnyis pa ka.rma bde
        chen dga' ba'i ye shes phrin las kun khyab dpal bzang po'i rnam par thar pa
        nyung tsam brjod pa skya ring 'char ka
      volume_number: 1
      total_pages: 116
      base_file: v001.txt
